// src/components/towerdefense/mathChallenges.js
//
// Mid-game "Maths Bolt" questions for the tower-defense arcade — the arithmetic
// counterpart to the Vocab Bolt. Each Year-7 unit has its own generator so the
// question always matches the skill the unit just taught (1.1 → integer
// add/sub, 1.4 → HCF, 1.6 → roots …). Questions are generated fresh every time,
// so the supply is endless no matter how long a run lasts.
//
// A generator returns { prompt, answer, choices? }:
//   prompt  — the question, display-ready (uses − U+2212, ×, ÷, √, ∛)
//   answer  — the canonical answer as written by the student ("3", "−7", "Yes")
//   choices — optional fixed option list (e.g. Yes/No); numeric questions get
//             plausible distractors generated by the caller when shown as MCQ.
//
// Answers are ALWAYS integers or Yes/No, so a 15-second popup never needs a
// calculator. Every generator is verified against an independent oracle in the
// build check (parses the prompt back and recomputes).

const MINUS = '−'; // − , the typographic minus, matched leniently on input

const ri = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;
// A non-zero pick from a range that spans zero, so products/quotients stay meaningful.
const nz = (min, max) => { const x = ri(min, max); return x === 0 ? ri(1, max) : x; };

function gcd(a, b) { a = Math.abs(a); b = Math.abs(b); while (b) { [a, b] = [b, a % b]; } return a || 1; }

// A signed integer for display: leading negatives use the typographic minus; a
// negative *operand after an operator* is wrapped in parentheses, textbook style.
const lead = (n) => (n < 0 ? `${MINUS}${Math.abs(n)}` : `${n}`);
const operand = (n) => (n < 0 ? `(${MINUS}${Math.abs(n)})` : `${n}`);

// 1.1 — Adding & Subtracting Integers
function intAddSub() {
  const a = ri(-12, 12);
  const b = ri(-12, 12);
  const add = Math.random() < 0.5;
  const answer = add ? a + b : a - b;
  return { prompt: `${lead(a)} ${add ? '+' : MINUS} ${operand(b)} = ?`, answer };
}

// 1.2 — Multiplying & Dividing Integers
function intMulDiv() {
  if (Math.random() < 0.5) {
    const a = nz(-9, 9);
    const b = nz(-9, 9);
    return { prompt: `${lead(a)} × ${operand(b)} = ?`, answer: a * b };
  }
  // Build the division from an exact quotient so it always divides cleanly.
  const q = nz(-9, 9);
  const d = ri(2, 9) * (Math.random() < 0.5 ? -1 : 1);
  return { prompt: `${lead(q * d)} ÷ ${operand(d)} = ?`, answer: q };
}

// 1.3 — Lowest Common Multiple
function lcm() {
  const a = ri(2, 9);
  const b = ri(2, 9);
  return { prompt: `LCM of ${a} and ${b} = ?`, answer: (a * b) / gcd(a, b) };
}

// 1.4 — Highest Common Factor (seeded with a shared factor so it isn't always 1)
function hcf() {
  const f = ri(2, 6);
  const a = f * ri(1, 6);
  const b = f * ri(1, 6);
  return { prompt: `HCF of ${a} and ${b} = ?`, answer: gcd(a, b) };
}

// 1.5 — Tests for Divisibility (Yes/No, ~50/50)
function divisibility() {
  const divisors = [2, 3, 4, 5, 6, 9, 10];
  const d = divisors[ri(0, divisors.length - 1)];
  let n;
  if (Math.random() < 0.5) {
    n = d * ri(2, 30); // guaranteed to divide
  } else {
    n = ri(10, 300);
    if (n % d === 0) n += 1; // nudge off a multiple (d ≥ 2 ⇒ n+1 can't also divide)
  }
  return { prompt: `Is ${n} divisible by ${d}?`, answer: n % d === 0 ? 'Yes' : 'No', choices: ['Yes', 'No'] };
}

// 1.6 — Square Roots & Cube Roots (perfect powers only)
function roots() {
  if (Math.random() < 0.6) {
    const r = ri(2, 12);
    return { prompt: `√${r * r} = ?`, answer: r };
  }
  const r = ri(2, 6);
  return { prompt: `∛${r * r * r} = ?`, answer: r };
}

// AM_3A — the Factor Theorem. Either substitute a small value into a cubic, or
// decide whether a linear expression is a factor. Both are the same move —
// "put x = c in and see what falls out" — which is exactly what makes the
// theorem quick enough for a fifteen-second popup. Coefficients are kept small
// so the arithmetic stays mental.
function factorTheorem() {
  const sup = { 2: '²', 3: '³' };
  const term = (coef, deg) => {
    if (coef === 0) return '';
    const mag = Math.abs(coef);
    const body = deg === 0 ? `${mag}` : `${mag === 1 ? '' : mag}x${sup[deg] || ''}`;
    return `${coef < 0 ? ` ${MINUS} ` : ' + '}${body}`;
  };
  // Leading coefficient is always 1, so the cubic reads like a textbook one.
  const b = ri(-4, 4);
  const c = ri(-6, 6);
  const k = [-2, -1, 1, 2][ri(0, 3)];
  const linear = k < 0 ? `(x + ${-k})` : `(x ${MINUS} ${k})`;
  const at = (dd) => k ** 3 + b * k ** 2 + c * k + dd;

  if (Math.random() < 0.55) {
    // Force P(k) = 0 half the time, and miss it by a little the rest.
    const isFactor = Math.random() < 0.5;
    const d = -(k ** 3 + b * k ** 2 + c * k) + (isFactor ? 0 : [1, -1, 2, -2, 3][ri(0, 4)]);
    const poly = `x³${term(b, 2)}${term(c, 1)}${term(d, 0)}`;
    return {
      prompt: `Is ${linear} a factor of ${poly}?`,
      answer: at(d) === 0 ? 'Yes' : 'No',
      choices: ['Yes', 'No'],
    };
  }
  const d = ri(-8, 8);
  const poly = `x³${term(b, 2)}${term(c, 1)}${term(d, 0)}`;
  const shown = k < 0 ? `${MINUS}${-k}` : `${k}`;
  return { prompt: `P(x) = ${poly}.  P(${shown}) = ?`, answer: at(d) };
}

/** unitId → question generator. Units with no entry get vocab-only challenges. */
export const MATH_CHALLENGE_GENERATORS = {
  AM_3A: factorTheorem,
  U01_1: intAddSub,
  U01_2: intMulDiv,
  U01_3: lcm,
  U01_4: hcf,
  U01_5: divisibility,
  U01_6: roots,
};

/** The generator for a unit, or null if it has none. */
export function mathChallengeFor(unitId) {
  return MATH_CHALLENGE_GENERATORS[unitId] || null;
}
