// src/components/towerdefense/mathChallenges.js
//
// Mid-game "Maths Bolt" questions for the tower-defense arcade — the arithmetic
// counterpart to the Vocab Bolt. Each Year-7 unit has its own generator so the
// question always matches the skill the unit just taught (1.1 → integer
// add/sub, 1.4 → HCF, 1.6 → roots …). Questions are generated fresh every time,
// so the supply is endless no matter how long a run lasts.
//
// A generator returns { prompt, answer, choices? }:
//   prompt  — the question, display-ready (uses − U+2212, ×, ÷, √, ∛)
//   answer  — the canonical answer as written by the student ("3", "−7", "Yes")
//   choices — optional fixed option list (e.g. Yes/No); numeric questions get
//             plausible distractors generated by the caller when shown as MCQ.
//
// Answers are integers or Yes/No, so a 15-second popup never needs a
// calculator — except Year 7 Unit 3 (powers of 10, rounding), whose answers are
// decimals and whose questions are therefore always multiple choice, with the
// unit's own slips as the wrong options (7.2000, 35 for 35.0) rather than n ± 1. Every generator is verified against an independent oracle in the
// build check (parses the prompt back and recomputes).

import { dec, decText, shift, roundTo, truncTo, canon } from '../../utils/decimal.js';

const MINUS = '−'; // − , the typographic minus, matched leniently on input

const ri = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;
// A non-zero pick from a range that spans zero, so products/quotients stay meaningful.
const nz = (min, max) => { const x = ri(min, max); return x === 0 ? ri(1, max) : x; };

function gcd(a, b) { a = Math.abs(a); b = Math.abs(b); while (b) { [a, b] = [b, a % b]; } return a || 1; }

// A signed integer for display: leading negatives use the typographic minus; a
// negative *operand after an operator* is wrapped in parentheses, textbook style.
const lead = (n) => (n < 0 ? `${MINUS}${Math.abs(n)}` : `${n}`);
const operand = (n) => (n < 0 ? `(${MINUS}${Math.abs(n)})` : `${n}`);

// 1.1 — Adding & Subtracting Integers
function intAddSub() {
  const a = ri(-12, 12);
  const b = ri(-12, 12);
  const add = Math.random() < 0.5;
  const answer = add ? a + b : a - b;
  return { prompt: `${lead(a)} ${add ? '+' : MINUS} ${operand(b)} = ?`, answer };
}

// 1.2 — Multiplying & Dividing Integers
function intMulDiv() {
  if (Math.random() < 0.5) {
    const a = nz(-9, 9);
    const b = nz(-9, 9);
    return { prompt: `${lead(a)} × ${operand(b)} = ?`, answer: a * b };
  }
  // Build the division from an exact quotient so it always divides cleanly.
  const q = nz(-9, 9);
  const d = ri(2, 9) * (Math.random() < 0.5 ? -1 : 1);
  return { prompt: `${lead(q * d)} ÷ ${operand(d)} = ?`, answer: q };
}

// 1.3 — Lowest Common Multiple
function lcm() {
  const a = ri(2, 9);
  const b = ri(2, 9);
  return { prompt: `LCM of ${a} and ${b} = ?`, answer: (a * b) / gcd(a, b) };
}

// 1.4 — Highest Common Factor (seeded with a shared factor so it isn't always 1)
function hcf() {
  const f = ri(2, 6);
  const a = f * ri(1, 6);
  const b = f * ri(1, 6);
  return { prompt: `HCF of ${a} and ${b} = ?`, answer: gcd(a, b) };
}

// 1.5 — Tests for Divisibility (Yes/No, ~50/50)
function divisibility() {
  const divisors = [2, 3, 4, 5, 6, 9, 10];
  const d = divisors[ri(0, divisors.length - 1)];
  let n;
  if (Math.random() < 0.5) {
    n = d * ri(2, 30); // guaranteed to divide
  } else {
    n = ri(10, 300);
    if (n % d === 0) n += 1; // nudge off a multiple (d ≥ 2 ⇒ n+1 can't also divide)
  }
  return { prompt: `Is ${n} divisible by ${d}?`, answer: n % d === 0 ? 'Yes' : 'No', choices: ['Yes', 'No'] };
}

// 1.6 — Square Roots & Cube Roots (perfect powers only)
function roots() {
  if (Math.random() < 0.6) {
    const r = ri(2, 12);
    return { prompt: `√${r * r} = ?`, answer: r };
  }
  const r = ri(2, 6);
  return { prompt: `∛${r * r * r} = ?`, answer: r };
}

// 2.6 — Inequalities. The smallest or largest integer that works (n ± 1 are
// exactly the slips: the circle's own number, and the wrong side), "could it
// be?" (Yes/No), or < against > between two numbers, usually negative.
function inequalities() {
  const letter = ['x', 'y', 't', 'n', 'p'][ri(0, 4)];
  const greater = Math.random() < 0.5;
  const n = ri(-9, 9);
  const roll = Math.random();
  if (roll < 0.45) {
    return {
      prompt: `${letter} ${greater ? '>' : '<'} ${lead(n)}. The ${greater ? 'smallest' : 'largest'} integer ${letter} could be = ?`,
      answer: greater ? n + 1 : n - 1,
    };
  }
  if (roll < 0.75) {
    const v = [n, greater ? n + 1 : n - 1, greater ? n - 1 : n + 1, greater ? n + ri(2, 20) : n - ri(2, 20)][ri(0, 3)];
    const works = greater ? v > n : v < n;
    return { prompt: `${letter} ${greater ? '>' : '<'} ${lead(n)}. Could ${letter} be ${lead(v)}?`, answer: works ? 'Yes' : 'No', choices: ['Yes', 'No'] };
  }
  const a = -ri(1, 12);
  let b = Math.random() < 0.6 ? -ri(1, 12) : ri(-9, 9);
  if (b === a) b += 1;
  return { prompt: `${lead(a)} □ ${lead(b)}: < or > ?`, answer: a < b ? '<' : '>', choices: ['<', '>'] };
}

// 3.1 — Multiplying & Dividing by Powers of 10. Either the calculation (always
// multiple choice: the wrong options are "just added zeros", the wrong way and
// one place out) or the missing power (a small whole number, typed or chosen).
function powersOfTen() {
  const SUP = ['', '', '²', '³', '⁴'];
  const pow = (p) => (p === 1 ? '10' : `10${SUP[p]}`);
  const shapes = ['3.4', '0.56', '72', '8', '1.25', '460', '0.9', '20.5', '6.1', '0.07', '5300', '14'];
  const n = shapes[ri(0, shapes.length - 1)];
  const p = ri(1, 3);
  const mul = Math.random() < 0.5;
  const v = dec(n);
  const at = (k) => decText(shift(v, k));
  const answer = at(mul ? p : -p);
  if (Math.random() < 0.3) {
    return { prompt: `${n} ${mul ? '×' : '÷'} 10ⁿ = ${answer}. What is n?`, answer: p };
  }
  const opts = new Set([answer]);
  if (mul && n.includes('.')) opts.add(`${n}${'0'.repeat(p)}`);           // zeros stuck on the end
  for (const k of [mul ? -p : p, mul ? p + 1 : -(p + 1), mul ? p - 1 : -(p - 1), mul ? p + 2 : -(p + 2)]) {
    if (opts.size >= 4) break;
    opts.add(at(k));
  }
  return { prompt: `${n} ${mul ? '×' : '÷'} ${pow(p)} = ?`, answer, choices: [...opts] };
}

// 3.2 — Rounding. Always multiple choice: the wrong options are the number
// chopped off, the trailing zero dropped, and the wrong place.
function rounding() {
  const whole = ri(1, 99);
  const places = [1, 1, 2, 0][ri(0, 3)];
  const frac = [ri(0, 9), ri(0, 9), ri(1, 9)];
  if (places >= 1 && Math.random() < 0.4) { frac[places - 1] = 9; frac[places] = ri(5, 9); }  // carries: keep the zero
  const n = `${whole}.${frac.join('')}`;
  const v = dec(n);
  const answer = decText(roundTo(v, places));
  const unit = { n: 1n, dp: places };
  const bump = (by) => decText({ n: roundTo(v, places).n + BigInt(by), dp: unit.dp });
  const opts = new Set([answer]);
  for (const o of [decText(truncTo(v, places)), decText(canon(roundTo(v, places))), decText(roundTo(v, places + 1)), bump(1), bump(-1)]) {
    if (opts.size >= 4) break;
    opts.add(o);
  }
  const to = places === 0 ? 'the nearest whole number' : `${places} d.p.`;
  return { prompt: `Round ${n} to ${to}`, answer, choices: [...opts] };
}

// AM_3A — the Factor Theorem. Either substitute a small value into a cubic, or
// decide whether a linear expression is a factor. Both are the same move —
// "put x = c in and see what falls out" — which is exactly what makes the
// theorem quick enough for a fifteen-second popup. Coefficients are kept small
// so the arithmetic stays mental.
function factorTheorem() {
  const sup = { 2: '²', 3: '³' };
  const term = (coef, deg) => {
    if (coef === 0) return '';
    const mag = Math.abs(coef);
    const body = deg === 0 ? `${mag}` : `${mag === 1 ? '' : mag}x${sup[deg] || ''}`;
    return `${coef < 0 ? ` ${MINUS} ` : ' + '}${body}`;
  };
  // Leading coefficient is always 1, so the cubic reads like a textbook one.
  const b = ri(-4, 4);
  const c = ri(-6, 6);
  const k = [-2, -1, 1, 2][ri(0, 3)];
  const linear = k < 0 ? `(x + ${-k})` : `(x ${MINUS} ${k})`;
  const at = (dd) => k ** 3 + b * k ** 2 + c * k + dd;

  if (Math.random() < 0.55) {
    // Force P(k) = 0 half the time, and miss it by a little the rest.
    const isFactor = Math.random() < 0.5;
    const d = -(k ** 3 + b * k ** 2 + c * k) + (isFactor ? 0 : [1, -1, 2, -2, 3][ri(0, 4)]);
    const poly = `x³${term(b, 2)}${term(c, 1)}${term(d, 0)}`;
    return {
      prompt: `Is ${linear} a factor of ${poly}?`,
      answer: at(d) === 0 ? 'Yes' : 'No',
      choices: ['Yes', 'No'],
    };
  }
  const d = ri(-8, 8);
  const poly = `x³${term(b, 2)}${term(c, 1)}${term(d, 0)}`;
  const shown = k < 0 ? `${MINUS}${-k}` : `${k}`;
  return { prompt: `P(x) = ${poly}.  P(${shown}) = ?`, answer: at(d) };
}

// AM_4A — Modulus Equations and Inequalities. Three moves, all of which a
// student who has done the unit can do in their head: evaluate a modulus, undo
// one (which is where the SECOND answer lives, and forgetting it is the mistake
// the unit exists to kill), and read the far end of a "less than" interval.
// Every answer is a whole number.
function modulus() {
  const r = Math.random();

  if (r < 0.4) {
    // Evaluate. The subtraction sits inside the bars half the time and outside
    // the other half, which is exactly the pair students confuse.
    const a = ri(-12, 12);
    const b = ri(-12, 12);
    if (Math.random() < 0.5) {
      return { prompt: `|${lead(a)} ${MINUS} ${operand(b)}| = ?`, answer: Math.abs(a - b) };
    }
    return { prompt: `|${lead(a)}| ${MINUS} |${lead(b)}| = ?`, answer: Math.abs(a) - Math.abs(b) };
  }

  if (r < 0.7) {
    // |x + b| = k. Asking for one named root forces the student to produce BOTH
    // and then pick, rather than stopping at the easy branch.
    const b = nz(-9, 9);
    const k = ri(1, 9);
    const roots = [-b - k, -b + k];
    const wantLarger = Math.random() < 0.5;
    const inner = b < 0 ? `x ${MINUS} ${Math.abs(b)}` : `x + ${b}`;
    return {
      prompt: `|${inner}| = ${k}.  ${wantLarger ? 'Larger' : 'Smaller'} value of x = ?`,
      answer: wantLarger ? roots[1] : roots[0],
    };
  }

  // |x − c| < k, largest or smallest INTEGER inside the interval. The interval
  // is c − k < x < c + k and the bounds are whole numbers, so the extreme
  // integers are one step inside them.
  const c = ri(-8, 8);
  const k = ri(2, 9);
  const wantLargest = Math.random() < 0.5;
  const inner = c < 0 ? `x + ${Math.abs(c)}` : `x ${MINUS} ${c}`;
  return {
    prompt: `|${inner}| < ${k}.  ${wantLargest ? 'Largest' : 'Smallest'} integer x = ?`,
    answer: wantLargest ? c + k - 1 : c - k + 1,
  };
}

// AM_4B — Sketching cubic graphs. Three reads off a factorised cubic that a
// student who has done the unit does in their head: a named x-intercept (the
// sign trap — (x + 2) crosses at −2), the y-intercept (multiply the constants,
// and the number in front), and which way the right-hand tail goes (the sign
// of the product of the x coefficients). The last one is Yes/No so that a
// fifteen-second popup never needs a full sketch.
function cubicSketch() {
  const lin = (p, q) => {
    const xPart = p === 1 ? 'x' : p === -1 ? `${MINUS}x` : `${p < 0 ? MINUS : ''}${Math.abs(p)}x`;
    if (q === 0) return xPart;
    return `${xPart} ${q < 0 ? MINUS : '+'} ${Math.abs(q)}`;
  };
  // Three distinct integer roots, one factor possibly written with 2x or a
  // negative x, exactly as Exercise 4.3 writes them.
  const roots = [];
  while (roots.length < 3) { const r = ri(-5, 5); if (!roots.includes(r)) roots.push(r); }
  const factors = roots.map((r, i) => {
    const p = i === 0 && Math.random() < 0.4 ? -1 : 1;
    return [p, -p * r];
  });
  const k = Math.random() < 0.3 ? -1 : 1;
  const text = `${k < 0 ? MINUS : ''}${factors.map(([p, q]) => `(${lin(p, q)})`).join('')}`;
  const r = Math.random();
  if (r < 0.4) {
    const want = Math.random() < 0.5 ? 'Largest' : 'Smallest';
    const sorted = [...roots].sort((a, b) => a - b);
    return { prompt: `y = ${text}.  ${want} x-intercept = ?`, answer: want === 'Largest' ? sorted[2] : sorted[0] };
  }
  if (r < 0.75) {
    const y = k * factors.reduce((acc, [, q]) => acc * q, 1);
    return { prompt: `y = ${text}.  y-intercept = ?`, answer: y };
  }
  const leadCoef = k * factors.reduce((acc, [p]) => acc * p, 1);
  return {
    prompt: `y = ${text}.  As x → +∞, does y → +∞?`,
    answer: leadCoef > 0 ? 'Yes' : 'No',
    choices: ['Yes', 'No'],
  };
}

// AM_5A — Logarithms and the laws of logs. Three reads a student who has done
// the unit does in their head, every answer a whole number: evaluate a log
// (a positive power, or a negative one from a unit fraction), and combine two
// logs of the same base — a sum or a difference — that land exactly on a power
// of the base. Subscript digits print the base the way the book does.
function logLaws() {
  const SUB = (n) => String(n).split('').map((d) => '₀₁₂₃₄₅₆₇₈₉'[Number(d)]).join('');
  const name = (b) => (b === 10 ? 'lg' : `log${SUB(b)}`);
  const pick = (list) => list[ri(0, list.length - 1)];
  const r = Math.random();
  if (r < 0.35) {
    // log_b(b^k), b^k kept small enough to know by heart.
    const [b, k] = pick([[2, ri(2, 7)], [3, ri(2, 4)], [5, ri(2, 3)], [10, ri(2, 5)], [4, ri(2, 3)], [7, 2]]);
    return { prompt: `${name(b)} ${b ** k} = ?`, answer: k };
  }
  if (r < 0.55) {
    // log_b(1 / b^k) = −k: the sign trap.
    const [b, k] = pick([[2, ri(1, 5)], [3, ri(1, 3)], [5, ri(1, 2)], [10, ri(1, 3)]]);
    return { prompt: `${name(b)} (1/${b ** k}) = ?`, answer: -k };
  }
  // Two logs that combine to b^k. Sum: split b^k into a factor pair.
  // Difference: b^k times a small multiplier, minus that multiplier.
  const [b, k] = pick([[2, ri(3, 6)], [3, ri(2, 4)], [10, ri(2, 3)], [5, 2], [6, 2]]);
  const target = b ** k;
  if (Math.random() < 0.5) {
    const pairs = [];
    for (let d = 2; d * d <= target; d += 1) if (target % d === 0 && d !== target / d) pairs.push([d, target / d]);
    if (pairs.length) {
      const [p, q] = pick(pairs);
      return { prompt: `${name(b)} ${p} + ${name(b)} ${q} = ?`, answer: k };
    }
  }
  const m = pick([3, 5, 7].filter((x) => x !== b));
  return { prompt: `${name(b)} ${target * m} ${MINUS} ${name(b)} ${m} = ?`, answer: k };
}

// AM_7A — The equation of a circle. Four reads a student who has done the unit
// does in their head: a coordinate of the centre (the sign trap — (x + 3)² puts
// the centre at x = −3), the radius (the square root of the right-hand side),
// the right-hand side for a given radius (squared, not doubled), and whether a
// point is on the circle (substitute it). The last is Yes/No, and its circles
// are built on Pythagorean triples so that "Yes" is reachable with whole numbers.
function circleEquation() {
  const br = (v, c) => (c === 0 ? `${v}²` : `(${v} ${c > 0 ? MINUS : '+'} ${Math.abs(c)})²`);
  const a = ri(-6, 6);
  const b = ri(-6, 6);
  const pick = Math.random();
  if (pick < 0.7) {
    const r = ri(2, 9);
    const eq = `${br('x', a)} + ${br('y', b)} = ${r * r}`;
    if (pick < 0.3) {
      const wantX = Math.random() < 0.5;
      return { prompt: `${eq}.  ${wantX ? 'x' : 'y'}-coordinate of the centre = ?`, answer: wantX ? a : b };
    }
    if (pick < 0.5) return { prompt: `${eq}.  Radius = ?`, answer: r };
    return { prompt: `Circle: centre (${lead(a)}, ${lead(b)}), radius ${r}.  Right-hand side of its equation = ?`, answer: r * r };
  }
  const [dx, dy, h] = [[3, 4, 5], [4, 3, 5], [6, 8, 10], [5, 12, 13], [0, 5, 5], [7, 0, 7]][ri(0, 5)];
  const on = Math.random() < 0.5;
  const px = a + (Math.random() < 0.5 ? dx : -dx);
  // Off the circle: one step up or down from a point that is on it.
  const py = b + (Math.random() < 0.5 ? dy : -dy) + (on ? 0 : (Math.random() < 0.5 ? 1 : -1));
  return {
    prompt: `${br('x', a)} + ${br('y', b)} = ${h * h}.  Is (${lead(px)}, ${lead(py)}) on the circle?`,
    answer: (px - a) ** 2 + (py - b) ** 2 === h * h ? 'Yes' : 'No',
    choices: ['Yes', 'No'],
  };
}

// AM_5B — Exponential equations, e and ln. Six reads a student who has done
// the unit does in their head: ln and e undoing each other (ln e⁴, ln(1/e²),
// e^(2 ln 3)), the number a shifted power brings with it (2^(x + 3) = 8 × 2ˣ),
// how many solutions a hidden quadratic REALLY has once each value of y is
// kept or rejected (the unit's thread — a power is never zero or negative),
// whether a power can equal a number at all, and the start value of a growth
// or decay model (e⁰ is 1). Answers are whole numbers or Yes/No; every
// quadratic is built from its two roots, so the count is always exact.
function expEquationBolt() {
  const SUP = { '-': '⁻', 0: '⁰', 1: '¹', 2: '²', 3: '³', 4: '⁴', 5: '⁵', 6: '⁶', 7: '⁷', 8: '⁸', 9: '⁹' };
  const sup = (n) => String(n).split('').map((ch) => SUP[ch]).join('');
  const pick = (list) => list[ri(0, list.length - 1)];
  const r = Math.random();
  if (r < 0.18) {
    if (Math.random() < 0.65) {
      const k = pick([-5, -4, -3, -2, -1, 2, 3, 4, 5, 6]);
      return { prompt: `ln(e${sup(k)}) = ?`, answer: k };
    }
    const k = ri(1, 4);
    return { prompt: `ln(1/e${k === 1 ? '' : sup(k)}) = ?`, answer: -k };
  }
  if (r < 0.32) {
    // e^(k ln n) = n^k, kept small enough to know by heart.
    const [k, n] = pick([[1, ri(2, 12)], [2, ri(2, 9)], [3, ri(2, 5)]]);
    return { prompt: `e^(${k === 1 ? '' : `${k} `}ln ${n}) = ?`, answer: n ** k };
  }
  if (r < 0.46) {
    // A shifted power splits: b^(x + s) = b^s × b^x.
    const [b, s] = pick([[2, 1], [2, 2], [2, 3], [2, 4], [3, 1], [3, 2], [3, 3], [5, 1], [5, 2], [10, 1], [10, 2]]);
    return { prompt: `${b}^(x + ${s}) = k × ${b}ˣ.  k = ?`, answer: b ** s };
  }
  if (r < 0.68) {
    // A hidden quadratic built from two different roots; only positive roots
    // give a value of x.
    const B = pick(['2', '3', 'e']);
    const roots = [-6, -5, -4, -3, -2, -1, 1, 2, 3, 4, 5, 6, 7, 8, 9];
    const r1 = pick(roots);
    let r2 = pick(roots);
    while (r2 === r1) r2 = pick(roots);
    const b = -(r1 + r2);
    const c = r1 * r2;
    // 5(2ˣ) and 5eˣ, the way the book prints them; a lone 2ˣ or eˣ needs no 1.
    const term = Math.abs(b) === 1 ? `${B}ˣ` : B === 'e' ? `${Math.abs(b)}eˣ` : `${Math.abs(b)}(${B}ˣ)`;
    const mid = b === 0 ? '' : ` ${b < 0 ? MINUS : '+'} ${term}`;
    const tail = ` ${c < 0 ? MINUS : '+'} ${Math.abs(c)}`;
    const count = [r1, r2].filter((v) => v > 0).length;
    return { prompt: `${B}²ˣ${mid}${tail} = 0.  How many solutions for x?`, answer: count };
  }
  if (r < 0.84) {
    // Can a power equal this number? Only a positive number, fraction or not.
    const B = pick(['2', '3', '5', 'e']);
    const v = pick(['1', '8', '20', '1/4', '1/9', '0', `${MINUS}4`, `${MINUS}1`, `${MINUS}1/2`, '3', '0']);
    const positive = !v.startsWith(MINUS) && v !== '0';
    return { prompt: `Does ${B}ˣ = ${v} have a solution?`, answer: positive ? 'Yes' : 'No', choices: ['Yes', 'No'] };
  }
  // The start value of a model: put t = 0, and e⁰ = 1.
  const letter = pick(['N', 'T', 'V', 'P']);
  const A = pick([40, 60, 80, 120, 150, 200, 250, 500]);
  const rate = pick(['0.1', '0.2', '0.3', '0.05', '0.04']);
  const decay = Math.random() < 0.6;
  const c = Math.random() < 0.4 ? pick([15, 20, 25]) : 0;
  return {
    prompt: `${letter} = ${A}e^(${decay ? MINUS : ''}${rate}t)${c ? ` + ${c}` : ''}.  ${letter} when t = 0?`,
    answer: A + c,
  };
}

// AM_5C — Log equations and change of base. Four reads a student who has done
// the unit does in their head: solve a one-log equation by exponential form,
// KEEP OR REJECT a root the algebra produced (the unit's thread — a log of a
// negative number, or a negative base, does not exist), cancel a chain of two
// logs, and the larger root of a quadratic in a log. Answers are whole
// numbers or Yes/No; every equation is built from its answer, so the numbers
// always come out.
function logEquationBolt() {
  const SUB = (n) => String(n).split('').map((d) => '₀₁₂₃₄₅₆₇₈₉'[Number(d)]).join('');
  const name = (b) => (b === 10 ? 'lg' : `log${SUB(b)}`);
  const pick = (list) => list[ri(0, list.length - 1)];
  const r = Math.random();
  if (r < 0.25) {
    // log_b(x ± c) = k, so x ± c = b^k.
    const [b, k] = pick([[2, ri(2, 5)], [3, ri(2, 3)], [5, 2], [10, ri(1, 2)], [4, 2], [7, 2]]);
    // Kept below b^k, so x itself is positive too and never looks like a root to reject.
    const c = ri(1, Math.min(9, b ** k - 1));
    const plus = Math.random() < 0.5;
    return { prompt: `${name(b)}(x ${plus ? '+' : MINUS} ${c}) = ${k}.  x = ?`, answer: plus ? b ** k - c : b ** k + c };
  }
  if (r < 0.6) {
    if (Math.random() < 0.3) {
      // log_x N = 2 gives x = ±√N; a base must be positive.
      const s = ri(2, 9);
      const askNeg = Math.random() < 0.6;
      const roots = Math.random() < 0.5 ? [s, -s] : [-s, s];
      return {
        prompt: `logₓ ${s * s} = 2 gives x = ${lead(roots[0])} or x = ${lead(roots[1])}.  Is x = ${lead(askNeg ? -s : s)} a solution?`,
        answer: askNeg ? 'No' : 'Yes',
        choices: ['Yes', 'No'],
      };
    }
    // log_b x + log_b(x + d) = k with roots p and −q, where pq = b^k and d = q − p.
    const [b, k] = pick([[2, 2], [2, 3], [2, 4], [3, 2], [3, 3], [5, 2], [10, 1], [10, 2]]);
    const N = b ** k;
    const pairs = [];
    for (let p = 1; p <= N; p += 1) if (N % p === 0 && p !== N / p) pairs.push([p, N / p]);
    const [p, q] = pick(pairs);
    const d = q - p;
    const second = d === 0 ? ' x' : `(x ${d > 0 ? '+' : MINUS} ${Math.abs(d)})`;
    const askNeg = Math.random() < 0.5;
    const roots = Math.random() < 0.5 ? [p, -q] : [-q, p];
    return {
      prompt: `${name(b)} x + ${name(b)}${second} = ${k} gives x = ${lead(roots[0])} or x = ${lead(roots[1])}.  Is x = ${lead(askNeg ? -q : p)} a solution?`,
      answer: askNeg ? 'No' : 'Yes',
      choices: ['Yes', 'No'],
    };
  }
  if (r < 0.8) {
    // log_a b × log_b(a^k) = k: the b cancels.
    const [a, k] = pick([[2, ri(2, 6)], [3, ri(2, 4)], [5, ri(2, 3)], [10, ri(2, 3)]]);
    const b = pick([3, 5, 6, 7, 11].filter((x) => x !== a));
    return { prompt: `${name(a)} ${b} × ${name(b)} ${a ** k} = ?`, answer: k };
  }
  // (log_b x)² − s log_b x + p = 0 with u = 1, 2 or 3: the larger x.
  const b = pick([2, 3]);
  const [u1, u2] = pick([[1, 2], [1, 3], [2, 3]]);
  return { prompt: `(${name(b)} x)² ${MINUS} ${u1 + u2} ${name(b)} x + ${u1 * u2} = 0.  Larger value of x = ?`, answer: b ** u2 };
}

// AM_5D — Graphs and inverses of exponential and log functions. Five reads a
// student who has done the unit does in their head: where y = k·e^(nx) + a
// crosses the y-axis (k + a — e⁰ is 1, not 0), the number in its asymptote
// (a), whether it crosses the x-axis at all (only when k and a have opposite
// signs: a power of e is never negative), and for y = k·ln(ax + b) the
// vertical asymptote (where the inside is 0) and whether the curve reaches the
// y-axis (only when the inside is positive at x = 0). Answers are whole
// numbers or Yes/No; the log's inside is built from its asymptote, so that
// always comes out whole.
function expLogGraphs() {
  const SUP = { '-': '⁻', x: 'ˣ', 0: '⁰', 1: '¹', 2: '²', 3: '³', 4: '⁴', 5: '⁵', 6: '⁶', 7: '⁷', 8: '⁸', 9: '⁹' };
  const pick = (list) => list[ri(0, list.length - 1)];
  const front = (k) => (k === 1 ? '' : k === -1 ? MINUS : lead(k));
  const tail = (c) => (c === 0 ? '' : ` ${c < 0 ? MINUS : '+'} ${Math.abs(c)}`);
  const r = Math.random();
  if (r < 0.6) {
    const k = nz(-5, 5);
    const n = pick([1, -1, 2, -2, 3]);
    const a = nz(-8, 8);
    const power = (n === 1 ? 'x' : n === -1 ? '-x' : `${n}x`).split('').map((ch) => SUP[ch] ?? ch).join('');
    const eq = `y = ${front(k)}e${power}${tail(a)}`;
    if (r < 0.2) return { prompt: `${eq}.  It crosses the y-axis at y = ?`, answer: k + a };
    if (r < 0.4) return { prompt: `${eq}.  Its asymptote is y = ?`, answer: a };
    return { prompt: `${eq}.  Does it cross the x-axis?`, answer: k * a < 0 ? 'Yes' : 'No', choices: ['Yes', 'No'] };
  }
  // y = k ln(ax + b), with the asymptote x = x0 chosen first and b = −a·x0.
  const k = pick([1, 2, 3, -1, -2]);
  const a = pick([1, 2, 3, -1, -2]);
  const x0 = ri(-5, 5);
  const b = x0 === 0 ? 0 : -a * x0;
  const ax = `${a === 1 ? '' : a === -1 ? MINUS : lead(a)}x`;
  const inside = b === 0 ? ax : a < 0 && b > 0 ? `${b} ${MINUS} ${a === -1 ? '' : -a}x` : `${ax}${tail(b)}`;
  const eq = `y = ${k === 1 ? '' : k === -1 ? MINUS : `${lead(k)} `}ln(${inside})`;
  if (r < 0.8) return { prompt: `${eq}.  Its asymptote is x = ?`, answer: x0 };
  return { prompt: `${eq}.  Does it cross the y-axis?`, answer: b > 0 ? 'Yes' : 'No', choices: ['Yes', 'No'] };
}

// PHYSICS / PHY_CIRC — Circular Motion & Gravity. Three shapes, all answered
// with a whole number: a unit conversion (the mark this unit loses most), a
// small centripetal force from F = mv²/r, and the minimum speed over the top
// v = √(gr) with g taken as 10 so the root is exact.
function circularMotion() {
  const r = Math.random();
  if (r < 0.4) {
    const kind = ri(0, 2);
    if (kind === 0) { const k = ri(2, 9); return { prompt: `${k} km = ? m`, answer: k * 1000 }; }
    if (kind === 1) { const h = ri(2, 5); return { prompt: `${h} hours = ? s`, answer: h * 3600 }; }
    const k = ri(2, 9);
    return { prompt: `${k} km/s = ? m/s`, answer: k * 1000 };
  }
  if (r < 0.75) {
    // Pick m and v, then a radius that divides m v² so F is whole.
    const m = ri(1, 5);
    const v = ri(2, 6);
    const mv2 = m * v * v;
    const divisors = [];
    for (let d = 1; d <= 12; d++) if (mv2 % d === 0) divisors.push(d);
    const rad = divisors[ri(0, divisors.length - 1)];
    return { prompt: `m = ${m} kg, v = ${v} m/s, r = ${rad} m.  F = mv²/r = ? N`, answer: mv2 / rad };
  }
  const k = ri(1, 5);
  return { prompt: `g = 10 m/s², r = ${10 * k * k} m.  Slowest speed over the top, v = √(gr) = ? m/s`, answer: 10 * k };
}

// PHYSICS / PHY_MOM — Momentum & Collisions. Four shapes, every answer a whole
// number WITH its sign, because the sign is the mark this unit loses: p = mv
// with a velocity that may point backwards, Δv across zero (minus a minus),
// two carts that stick together (one at rest), and a recoil from rest.
function momentum() {
  const r = Math.random();
  if (r < 0.3) {
    const m = ri(2, 12);
    const v = nz(-9, 9);
    return { prompt: `m = ${m} kg, v = ${lead(v)} m/s.  p = mv = ? kg·m/s`, answer: m * v };
  }
  if (r < 0.55) {
    // The ball turns round: one velocity each side of zero.
    const a = ri(2, 12), b = ri(2, 12);
    const [vi, vf] = Math.random() < 0.5 ? [-a, b] : [a, -b];
    return { prompt: `v_i = ${lead(vi)} m/s, v_f = ${lead(vf)} m/s.  Δv = v_f ${MINUS} v_i = ?`, answer: vf - vi };
  }
  if (r < 0.8) {
    // v_f = m₁v₁ / (m₁ + m₂), built backwards so it is whole: v₁ = k(m₁ + m₂).
    const m1 = ri(1, 5), m2 = ri(1, 5), k = ri(1, 4);
    const v1 = k * (m1 + m2);
    return { prompt: `${m1} kg at ${v1} m/s hits ${m2} kg at rest. They stick.  v_f = ? m/s`, answer: k * m1 };
  }
  // Recoil: m₁v₁ = −m₂v₂. Pick the pushed-off ball's momentum, then a cart mass that divides it.
  const m2 = ri(1, 4), v2 = ri(3, 12);
  const p = m2 * v2;
  const masses = [];
  for (let d = 2; d <= 12; d++) if (p % d === 0 && d !== m2) masses.push(d);
  const m1 = masses.length ? masses[ri(0, masses.length - 1)] : p;
  return { prompt: `From rest, a cart (${m1} kg) pushes off a ${m2} kg ball. Ball: +${v2} m/s.  Cart v = ? m/s`, answer: -p / m1 };
}

// EXT_MATH / EM_06 — Sets, Surds and Rationalising. Four reads a student who
// has done the unit does in their head: the number that comes OUT of a root,
// a region of a Venn diagram whose counts are given in the prompt, the number
// in front after clearing a single surd from a denominator, and a conjugate
// pair (which is always a whole number). Every answer is an integer.
function setsAndSurds() {
  const FREE = [2, 3, 5, 6, 7, 10, 11, 13, 14, 15]; // square-free radicands
  const r = Math.random();
  if (r < 0.35) {
    // √(a²b) = a√b — asks for a, the number that comes out.
    const b = FREE[ri(0, FREE.length - 1)];
    const a = ri(2, Math.max(2, Math.floor(Math.sqrt(400 / b))));
    return { prompt: `√${a * a * b} = a√${b}.  a = ?`, answer: a };
  }
  if (r < 0.6) {
    // A two-set Venn diagram, counts given in words.
    const aOnly = ri(3, 15);
    const both = ri(1, 9);
    const bOnly = ri(3, 15);
    const out = ri(0, 8);
    const kind = ri(0, 2);
    const stem = `A only ${aOnly}, both ${both}, B only ${bOnly}, outside ${out}.`;
    if (kind === 0) return { prompt: `${stem}  n(A ∪ B) = ?`, answer: aOnly + both + bOnly };
    if (kind === 1) return { prompt: `${stem}  n(A) = ?`, answer: aOnly + both };
    return { prompt: `${stem}  n(ℰ) = ?`, answer: aOnly + both + bOnly + out };
  }
  if (r < 0.8) {
    // am/√m = a√m — asks for the number in front after rationalising.
    const m = [2, 3, 5, 6, 7][ri(0, 4)];
    const a = ri(2, 6);
    return { prompt: `${a * m}/√${m} = a√${m}.  a = ?`, answer: a };
  }
  // A conjugate pair: p² − m, always a whole number.
  const m = [2, 3, 5, 6, 7, 10][ri(0, 5)];
  const p = ri(3, 9);
  return { prompt: `(${p} + √${m})(${p} ${MINUS} √${m}) = ?`, answer: p * p - m };
}

// EXT_MATH / EM_07A — Bounds, Inequalities & Simultaneous Equations. Three
// reads a student who has done the unit does in their head: a bound of a
// value rounded to the nearest 10, the smallest whole number an inequality
// allows, and one value of a simple pair of simultaneous equations. Every
// answer is an integer.
function inequalitiesSimultaneous() {
  const r = Math.random();
  if (r < 0.3) {
    // A whole number rounded to the nearest 10: the bounds are 5 either side.
    const n = ri(3, 60) * 10;
    return Math.random() < 0.5
      ? { prompt: `${n} m to the nearest 10 m. Upper bound = ? m`, answer: n + 5 }
      : { prompt: `${n} m to the nearest 10 m. Lower bound = ? m`, answer: n - 5 };
  }
  if (r < 0.65) {
    // ax + b > c with c = a·x0 + b, so x > x0 and the smallest whole x is x0 + 1.
    const a = ri(2, 6);
    const x0 = ri(-5, 8);
    const b = nz(-9, 9);
    const c = a * x0 + b;
    return { prompt: `${a}x ${b < 0 ? MINUS : '+'} ${Math.abs(b)} > ${lead(c)}. Smallest whole number x = ?`, answer: x0 + 1 };
  }
  const x = ri(1, 12);
  const y = ri(1, 12);
  const askX = Math.random() < 0.5;
  return { prompt: `x + y = ${x + y}, x ${MINUS} y = ${lead(x - y)}. ${askX ? 'x' : 'y'} = ?`, answer: askX ? x : y };
}

// EXT_MATH / EM_07B — Bearings, Trigonometry & Scatter Graphs. Three reads
// done in the head: a back bearing (either way round), the hypotenuse of a
// Pythagorean triple, and the sides of a regular polygon from one of its
// angles. Every answer is an integer — the trigonometry itself needs a
// calculator, so it stays in the Triangle Solver.
const PYTHAG_TRIPLES = [[3, 4, 5], [6, 8, 10], [5, 12, 13], [9, 12, 15], [8, 15, 17], [12, 16, 20], [7, 24, 25]];
const POLYGON_SIDES = [3, 4, 5, 6, 8, 9, 10, 12, 15, 18, 20];
function bearingsTrig() {
  const r = Math.random();
  if (r < 0.36) {
    const b = Math.random() < 0.5 ? ri(10, 170) : ri(190, 350);
    return { prompt: `Bearing of B from A is ${String(b).padStart(3, '0')}°. Bearing of A from B = ?°`, answer: b < 180 ? b + 180 : b - 180 };
  }
  if (r < 0.68) {
    const [a, b, c] = PYTHAG_TRIPLES[ri(0, PYTHAG_TRIPLES.length - 1)];
    return { prompt: `Right-angled triangle, shorter sides ${a} and ${b}. Hypotenuse = ?`, answer: c };
  }
  const n = POLYGON_SIDES[ri(0, POLYGON_SIDES.length - 1)];
  const ext = 360 / n;
  return Math.random() < 0.5
    ? { prompt: `Regular polygon, exterior angle ${ext}°. Number of sides = ?`, answer: n }
    : { prompt: `Regular polygon, interior angle ${180 - ext}°. Number of sides = ?`, answer: n };
}

/** unitId → question generator. Units with no entry get vocab-only challenges. */
export const MATH_CHALLENGE_GENERATORS = {
  EM_06: setsAndSurds,
  EM_07A: inequalitiesSimultaneous,
  EM_07B: bearingsTrig,
  PHY_CIRC: circularMotion,
  PHY_MOM: momentum,
  AM_3A: factorTheorem,
  AM_4A: modulus,
  AM_4B: cubicSketch,
  AM_5A: logLaws,
  AM_7A: circleEquation,
  AM_5B: expEquationBolt,
  AM_5C: logEquationBolt,
  AM_5D: expLogGraphs,
  U01_1: intAddSub,
  U01_2: intMulDiv,
  U01_3: lcm,
  U01_4: hcf,
  U01_5: divisibility,
  U01_6: roots,
  U02_6: inequalities,
  U03_1: powersOfTen,
  U03_2: rounding,
};

/**
 * Unit ids are only unique WITHIN a track — Year 7 Science also has U01_1 to
 * U01_4 — so a caller that knows the track should say so, or a student studying
 * cells gets integer arithmetic. Generators not listed here have ids no other
 * track uses.
 */
const GENERATOR_TRACK = {
  U01_1: 'Y7_MATH', U01_2: 'Y7_MATH', U01_3: 'Y7_MATH',
  U01_4: 'Y7_MATH', U01_5: 'Y7_MATH', U01_6: 'Y7_MATH',
  U02_6: 'Y7_MATH', U03_1: 'Y7_MATH', U03_2: 'Y7_MATH',
};

/** True when `unitId` in `track` is the unit a generator was written for. */
export function hasMathChallenge(track, unitId) {
  if (!MATH_CHALLENGE_GENERATORS[unitId]) return false;
  const owner = GENERATOR_TRACK[unitId];
  return !owner || owner === track;
}

/** The generator for a unit, or null if it has none. */
export function mathChallengeFor(unitId) {
  return MATH_CHALLENGE_GENERATORS[unitId] || null;
}
