// src/components/towerdefense/mathChallenges.js
//
// Mid-game "Maths Bolt" questions for the tower-defense arcade — the arithmetic
// counterpart to the Vocab Bolt. Each Year-7 unit has its own generator so the
// question always matches the skill the unit just taught (1.1 → integer
// add/sub, 1.4 → HCF, 1.6 → roots …). Questions are generated fresh every time,
// so the supply is endless no matter how long a run lasts.
//
// A generator returns { prompt, answer, choices? }:
//   prompt  — the question, display-ready (uses − U+2212, ×, ÷, √, ∛)
//   answer  — the canonical answer as written by the student ("3", "−7", "Yes")
//   choices — optional fixed option list (e.g. Yes/No); numeric questions get
//             plausible distractors generated by the caller when shown as MCQ.
//
// Answers are ALWAYS integers or Yes/No, so a 15-second popup never needs a
// calculator. Every generator is verified against an independent oracle in the
// build check (parses the prompt back and recomputes).

const MINUS = '−'; // − , the typographic minus, matched leniently on input

const ri = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;
// A non-zero pick from a range that spans zero, so products/quotients stay meaningful.
const nz = (min, max) => { const x = ri(min, max); return x === 0 ? ri(1, max) : x; };

function gcd(a, b) { a = Math.abs(a); b = Math.abs(b); while (b) { [a, b] = [b, a % b]; } return a || 1; }

// A signed integer for display: leading negatives use the typographic minus; a
// negative *operand after an operator* is wrapped in parentheses, textbook style.
const lead = (n) => (n < 0 ? `${MINUS}${Math.abs(n)}` : `${n}`);
const operand = (n) => (n < 0 ? `(${MINUS}${Math.abs(n)})` : `${n}`);

// 1.1 — Adding & Subtracting Integers
function intAddSub() {
  const a = ri(-12, 12);
  const b = ri(-12, 12);
  const add = Math.random() < 0.5;
  const answer = add ? a + b : a - b;
  return { prompt: `${lead(a)} ${add ? '+' : MINUS} ${operand(b)} = ?`, answer };
}

// 1.2 — Multiplying & Dividing Integers
function intMulDiv() {
  if (Math.random() < 0.5) {
    const a = nz(-9, 9);
    const b = nz(-9, 9);
    return { prompt: `${lead(a)} × ${operand(b)} = ?`, answer: a * b };
  }
  // Build the division from an exact quotient so it always divides cleanly.
  const q = nz(-9, 9);
  const d = ri(2, 9) * (Math.random() < 0.5 ? -1 : 1);
  return { prompt: `${lead(q * d)} ÷ ${operand(d)} = ?`, answer: q };
}

// 1.3 — Lowest Common Multiple
function lcm() {
  const a = ri(2, 9);
  const b = ri(2, 9);
  return { prompt: `LCM of ${a} and ${b} = ?`, answer: (a * b) / gcd(a, b) };
}

// 1.4 — Highest Common Factor (seeded with a shared factor so it isn't always 1)
function hcf() {
  const f = ri(2, 6);
  const a = f * ri(1, 6);
  const b = f * ri(1, 6);
  return { prompt: `HCF of ${a} and ${b} = ?`, answer: gcd(a, b) };
}

// 1.5 — Tests for Divisibility (Yes/No, ~50/50)
function divisibility() {
  const divisors = [2, 3, 4, 5, 6, 9, 10];
  const d = divisors[ri(0, divisors.length - 1)];
  let n;
  if (Math.random() < 0.5) {
    n = d * ri(2, 30); // guaranteed to divide
  } else {
    n = ri(10, 300);
    if (n % d === 0) n += 1; // nudge off a multiple (d ≥ 2 ⇒ n+1 can't also divide)
  }
  return { prompt: `Is ${n} divisible by ${d}?`, answer: n % d === 0 ? 'Yes' : 'No', choices: ['Yes', 'No'] };
}

// 1.6 — Square Roots & Cube Roots (perfect powers only)
function roots() {
  if (Math.random() < 0.6) {
    const r = ri(2, 12);
    return { prompt: `√${r * r} = ?`, answer: r };
  }
  const r = ri(2, 6);
  return { prompt: `∛${r * r * r} = ?`, answer: r };
}

// AM_3A — the Factor Theorem. Either substitute a small value into a cubic, or
// decide whether a linear expression is a factor. Both are the same move —
// "put x = c in and see what falls out" — which is exactly what makes the
// theorem quick enough for a fifteen-second popup. Coefficients are kept small
// so the arithmetic stays mental.
function factorTheorem() {
  const sup = { 2: '²', 3: '³' };
  const term = (coef, deg) => {
    if (coef === 0) return '';
    const mag = Math.abs(coef);
    const body = deg === 0 ? `${mag}` : `${mag === 1 ? '' : mag}x${sup[deg] || ''}`;
    return `${coef < 0 ? ` ${MINUS} ` : ' + '}${body}`;
  };
  // Leading coefficient is always 1, so the cubic reads like a textbook one.
  const b = ri(-4, 4);
  const c = ri(-6, 6);
  const k = [-2, -1, 1, 2][ri(0, 3)];
  const linear = k < 0 ? `(x + ${-k})` : `(x ${MINUS} ${k})`;
  const at = (dd) => k ** 3 + b * k ** 2 + c * k + dd;

  if (Math.random() < 0.55) {
    // Force P(k) = 0 half the time, and miss it by a little the rest.
    const isFactor = Math.random() < 0.5;
    const d = -(k ** 3 + b * k ** 2 + c * k) + (isFactor ? 0 : [1, -1, 2, -2, 3][ri(0, 4)]);
    const poly = `x³${term(b, 2)}${term(c, 1)}${term(d, 0)}`;
    return {
      prompt: `Is ${linear} a factor of ${poly}?`,
      answer: at(d) === 0 ? 'Yes' : 'No',
      choices: ['Yes', 'No'],
    };
  }
  const d = ri(-8, 8);
  const poly = `x³${term(b, 2)}${term(c, 1)}${term(d, 0)}`;
  const shown = k < 0 ? `${MINUS}${-k}` : `${k}`;
  return { prompt: `P(x) = ${poly}.  P(${shown}) = ?`, answer: at(d) };
}

// AM_4A — Modulus Equations and Inequalities. Three moves, all of which a
// student who has done the unit can do in their head: evaluate a modulus, undo
// one (which is where the SECOND answer lives, and forgetting it is the mistake
// the unit exists to kill), and read the far end of a "less than" interval.
// Every answer is a whole number.
function modulus() {
  const r = Math.random();

  if (r < 0.4) {
    // Evaluate. The subtraction sits inside the bars half the time and outside
    // the other half, which is exactly the pair students confuse.
    const a = ri(-12, 12);
    const b = ri(-12, 12);
    if (Math.random() < 0.5) {
      return { prompt: `|${lead(a)} ${MINUS} ${operand(b)}| = ?`, answer: Math.abs(a - b) };
    }
    return { prompt: `|${lead(a)}| ${MINUS} |${lead(b)}| = ?`, answer: Math.abs(a) - Math.abs(b) };
  }

  if (r < 0.7) {
    // |x + b| = k. Asking for one named root forces the student to produce BOTH
    // and then pick, rather than stopping at the easy branch.
    const b = nz(-9, 9);
    const k = ri(1, 9);
    const roots = [-b - k, -b + k];
    const wantLarger = Math.random() < 0.5;
    const inner = b < 0 ? `x ${MINUS} ${Math.abs(b)}` : `x + ${b}`;
    return {
      prompt: `|${inner}| = ${k}.  ${wantLarger ? 'Larger' : 'Smaller'} value of x = ?`,
      answer: wantLarger ? roots[1] : roots[0],
    };
  }

  // |x − c| < k, largest or smallest INTEGER inside the interval. The interval
  // is c − k < x < c + k and the bounds are whole numbers, so the extreme
  // integers are one step inside them.
  const c = ri(-8, 8);
  const k = ri(2, 9);
  const wantLargest = Math.random() < 0.5;
  const inner = c < 0 ? `x + ${Math.abs(c)}` : `x ${MINUS} ${c}`;
  return {
    prompt: `|${inner}| < ${k}.  ${wantLargest ? 'Largest' : 'Smallest'} integer x = ?`,
    answer: wantLargest ? c + k - 1 : c - k + 1,
  };
}

// AM_4B — Sketching cubic graphs. Three reads off a factorised cubic that a
// student who has done the unit does in their head: a named x-intercept (the
// sign trap — (x + 2) crosses at −2), the y-intercept (multiply the constants,
// and the number in front), and which way the right-hand tail goes (the sign
// of the product of the x coefficients). The last one is Yes/No so that a
// fifteen-second popup never needs a full sketch.
function cubicSketch() {
  const lin = (p, q) => {
    const xPart = p === 1 ? 'x' : p === -1 ? `${MINUS}x` : `${p < 0 ? MINUS : ''}${Math.abs(p)}x`;
    if (q === 0) return xPart;
    return `${xPart} ${q < 0 ? MINUS : '+'} ${Math.abs(q)}`;
  };
  // Three distinct integer roots, one factor possibly written with 2x or a
  // negative x, exactly as Exercise 4.3 writes them.
  const roots = [];
  while (roots.length < 3) { const r = ri(-5, 5); if (!roots.includes(r)) roots.push(r); }
  const factors = roots.map((r, i) => {
    const p = i === 0 && Math.random() < 0.4 ? -1 : 1;
    return [p, -p * r];
  });
  const k = Math.random() < 0.3 ? -1 : 1;
  const text = `${k < 0 ? MINUS : ''}${factors.map(([p, q]) => `(${lin(p, q)})`).join('')}`;
  const r = Math.random();
  if (r < 0.4) {
    const want = Math.random() < 0.5 ? 'Largest' : 'Smallest';
    const sorted = [...roots].sort((a, b) => a - b);
    return { prompt: `y = ${text}.  ${want} x-intercept = ?`, answer: want === 'Largest' ? sorted[2] : sorted[0] };
  }
  if (r < 0.75) {
    const y = k * factors.reduce((acc, [, q]) => acc * q, 1);
    return { prompt: `y = ${text}.  y-intercept = ?`, answer: y };
  }
  const leadCoef = k * factors.reduce((acc, [p]) => acc * p, 1);
  return {
    prompt: `y = ${text}.  As x → +∞, does y → +∞?`,
    answer: leadCoef > 0 ? 'Yes' : 'No',
    choices: ['Yes', 'No'],
  };
}

// PHYSICS / PHY_CIRC — Circular Motion & Gravity. Three shapes, all answered
// with a whole number: a unit conversion (the mark this unit loses most), a
// small centripetal force from F = mv²/r, and the minimum speed over the top
// v = √(gr) with g taken as 10 so the root is exact.
function circularMotion() {
  const r = Math.random();
  if (r < 0.4) {
    const kind = ri(0, 2);
    if (kind === 0) { const k = ri(2, 9); return { prompt: `${k} km = ? m`, answer: k * 1000 }; }
    if (kind === 1) { const h = ri(2, 5); return { prompt: `${h} hours = ? s`, answer: h * 3600 }; }
    const k = ri(2, 9);
    return { prompt: `${k} km/s = ? m/s`, answer: k * 1000 };
  }
  if (r < 0.75) {
    // Pick m and v, then a radius that divides m v² so F is whole.
    const m = ri(1, 5);
    const v = ri(2, 6);
    const mv2 = m * v * v;
    const divisors = [];
    for (let d = 1; d <= 12; d++) if (mv2 % d === 0) divisors.push(d);
    const rad = divisors[ri(0, divisors.length - 1)];
    return { prompt: `m = ${m} kg, v = ${v} m/s, r = ${rad} m.  F = mv²/r = ? N`, answer: mv2 / rad };
  }
  const k = ri(1, 5);
  return { prompt: `g = 10 m/s², r = ${10 * k * k} m.  Slowest speed over the top, v = √(gr) = ? m/s`, answer: 10 * k };
}

/** unitId → question generator. Units with no entry get vocab-only challenges. */
export const MATH_CHALLENGE_GENERATORS = {
  PHY_CIRC: circularMotion,
  AM_3A: factorTheorem,
  AM_4A: modulus,
  AM_4B: cubicSketch,
  U01_1: intAddSub,
  U01_2: intMulDiv,
  U01_3: lcm,
  U01_4: hcf,
  U01_5: divisibility,
  U01_6: roots,
};

/** The generator for a unit, or null if it has none. */
export function mathChallengeFor(unitId) {
  return MATH_CHALLENGE_GENERATORS[unitId] || null;
}
